/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LogRouteImport } from './routes/log'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as FinanceAccountsRouteImport } from './routes/finance/accounts'
import { Route as FinanceBudgetsRouteImport } from './routes/finance/budgets'
import { Route as FinanceCurrenciesRouteImport } from './routes/finance/currencies'
import { Route as FinanceSpendingRouteImport } from './routes/finance/spending'
import { Route as FinanceTransactionsRouteImport } from './routes/finance/transactions'
import { Route as HabitsIndexRouteImport } from './routes/habits/index'
import { Route as HabitsTodayRouteImport } from './routes/habits/today'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/finance/accounts',
  path: '/finance/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/finance/budgets',
  path: '/finance/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCurrenciesRoute = FinanceCurrenciesRouteImport.update({
  id: '/finance/currencies',
  path: '/finance/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceSpendingRoute = FinanceSpendingRouteImport.update({
  id: '/finance/spending',
  path: '/finance/spending',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/finance/transactions',
  path: '/finance/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsTodayRoute = HabitsTodayRouteImport.update({
  id: '/habits/today',
  path: '/habits/today',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/log': typeof LogRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/currencies': typeof FinanceCurrenciesRoute
  '/finance/spending': typeof FinanceSpendingRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/habits/today': typeof HabitsTodayRoute
  '/finance/': typeof FinanceIndexRoute
  '/habits/': typeof HabitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/log': typeof LogRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/currencies': typeof FinanceCurrenciesRoute
  '/finance/spending': typeof FinanceSpendingRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/habits/today': typeof HabitsTodayRoute
  '/finance': typeof FinanceIndexRoute
  '/habits': typeof HabitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/log': typeof LogRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/currencies': typeof FinanceCurrenciesRoute
  '/finance/spending': typeof FinanceSpendingRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/habits/today': typeof HabitsTodayRoute
  '/finance/': typeof FinanceIndexRoute
  '/habits/': typeof HabitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journal'
    | '/log'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/currencies'
    | '/finance/spending'
    | '/finance/transactions'
    | '/habits/today'
    | '/finance/'
    | '/habits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journal'
    | '/log'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/currencies'
    | '/finance/spending'
    | '/finance/transactions'
    | '/habits/today'
    | '/finance'
    | '/habits'
  id:
    | '__root__'
    | '/'
    | '/journal'
    | '/log'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/currencies'
    | '/finance/spending'
    | '/finance/transactions'
    | '/habits/today'
    | '/finance/'
    | '/habits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JournalRoute: typeof JournalRoute
  LogRoute: typeof LogRoute
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceBudgetsRoute: typeof FinanceBudgetsRoute
  FinanceCurrenciesRoute: typeof FinanceCurrenciesRoute
  FinanceSpendingRoute: typeof FinanceSpendingRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  HabitsTodayRoute: typeof HabitsTodayRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/finance/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/finance/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/currencies': {
      id: '/finance/currencies'
      path: '/finance/currencies'
      fullPath: '/finance/currencies'
      preLoaderRoute: typeof FinanceCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/spending': {
      id: '/finance/spending'
      path: '/finance/spending'
      fullPath: '/finance/spending'
      preLoaderRoute: typeof FinanceSpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/': {
      id: '/habits/'
      path: '/habits'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/today': {
      id: '/habits/today'
      path: '/habits/today'
      fullPath: '/habits/today'
      preLoaderRoute: typeof HabitsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JournalRoute: JournalRoute,
  LogRoute: LogRoute,
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceBudgetsRoute: FinanceBudgetsRoute,
  FinanceCurrenciesRoute: FinanceCurrenciesRoute,
  FinanceSpendingRoute: FinanceSpendingRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  HabitsTodayRoute: HabitsTodayRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  HabitsIndexRoute: HabitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
